### ISSUE TITLE
 TypeError: Cannot read property 'references' of undefined

### ISSUE THREAD

**Issue by mlopes** [gsuitedevs/md2googleslides#19]
Using node v9.8.0, it seems to fail when trying to convert the document:

```
Unable to generate slides: TypeError: Cannot read property 'references' of undefined
    at Array.link (/usr/lib/node_modules/md2gslides/node_modules/markdown-it/lib/rules_inline/link.js:101:26)
    at ParserInline.tokenize (/usr/lib/node_modules/md2gslides/node_modules/markdown-it/lib/parser_inline.js:135:22)
    at ParserInline.parse (/usr/lib/node_modules/md2gslides/node_modules/markdown-it/lib/parser_inline.js:163:8)
    at Array.inline (/usr/lib/node_modules/md2gslides/node_modules/markdown-it/lib/rules_core/inline.js:10:23)
    at Core.process (/usr/lib/node_modules/md2gslides/node_modules/markdown-it/lib/parser_core.js:51:13)
    at MarkdownIt.parse (/usr/lib/node_modules/md2gslides/node_modules/markdown-it/lib/index.js:523:13)
    at parseMarkdown (/usr/lib/node_modules/md2gslides/lib/extract_slides.js:77:19)
    at extractSlides (/usr/lib/node_modules/md2gslides/lib/extract_slides.js:56:18)
    at SlideGenerator.generateFromMarkdown (/usr/lib/node_modules/md2gslides/lib/slide_generator.js:86:27)
    at generateSlides (/usr/lib/node_modules/md2gslides/bin/md2gslides.js:177:27)
    at tryCallOne (/usr/lib/node_modules/md2gslides/node_modules/promise/lib/core.js:37:12)
    at /usr/lib/node_modules/md2gslides/node_modules/promise/lib/core.js:123:15
    at flush (/usr/lib/node_modules/md2gslides/node_modules/asap/raw.js:50:29)
    at process._tickCallback (internal/process/next_tick.js:112:11)
TypeError: Cannot read property 'references' of undefined
    at Array.link (/usr/lib/node_modules/md2gslides/node_modules/markdown-it/lib/rules_inline/link.js:101:26)
    at ParserInline.tokenize (/usr/lib/node_modules/md2gslides/node_modules/markdown-it/lib/parser_inline.js:135:22)
    at ParserInline.parse (/usr/lib/node_modules/md2gslides/node_modules/markdown-it/lib/parser_inline.js:163:8)
    at Array.inline (/usr/lib/node_modules/md2gslides/node_modules/markdown-it/lib/rules_core/inline.js:10:23)
    at Core.process (/usr/lib/node_modules/md2gslides/node_modules/markdown-it/lib/parser_core.js:51:13)
    at MarkdownIt.parse (/usr/lib/node_modules/md2gslides/node_modules/markdown-it/lib/index.js:523:13)
    at parseMarkdown (/usr/lib/node_modules/md2gslides/lib/extract_slides.js:77:19)
    at extractSlides (/usr/lib/node_modules/md2gslides/lib/extract_slides.js:56:18)
    at SlideGenerator.generateFromMarkdown (/usr/lib/node_modules/md2gslides/lib/slide_generator.js:86:27)
    at generateSlides (/usr/lib/node_modules/md2gslides/bin/md2gslides.js:177:27)
    at tryCallOne (/usr/lib/node_modules/md2gslides/node_modules/promise/lib/core.js:37:12)
    at /usr/lib/node_modules/md2gslides/node_modules/promise/lib/core.js:123:15
    at flush (/usr/lib/node_modules/md2gslides/node_modules/asap/raw.js:50:29)
    at process._tickCallback (internal/process/next_tick.js:112:11)
{}
```

**Comment by accorvin** [comment]
I was experiencing this same issue and finally determined that there were invalid/incomplete markdown references in the markdown file I was attempting to use to create the slides.

**Comment by sqrrrl** [comment]
I've been unable to reproduce this (or inadvertently fixed it.) If either of you can provide a sample markdown file that reproduces this, please re-open.
