### ISSUE TITLE
Error when trying to export supported markdown

### ISSUE THREAD

**Issue by zenmaster24** [gsuitedevs/md2googleslides#38]
Hi,

I am using the as slides.md and getting a #comment error:

```
# This is a title slide
## Your name here
---
# This is a section title
---
# Section title & body slide
## This is a subtitle
This is the body
---
# Title & body slide
This is the slide body.
---
# This is the main point {.big}
---
# 100% {.big}
This is the body
---
# Two column layout
This is the left column
{.column}
This is the right column
---
# Slides can have images
![](https://placekitten.com/900/900)
---
# Slides can have background images
![](https://placekitten.com/1600/900){.background}
---
# Slides can have videos
@[youtube](MG8KADiRbOU)
---
# Slide title
![](https://placekitten.com/1600/900){.background}
<!--
These are speaker notes.
-->
---
**Bold**, *italics*, and ~~strikethrough~~ may be used.

Ordered lists:
1. Item 1
1. Item 2
  1. Item 2.1

Unordered lists:
* Item 1
* Item 2
  * Item 2.1
---
### I :heart: cats
:heart_eyes_cat:
---
### Hello World
```javascript
console.log('Hello world');
```

Error:
```
Unable to generate slides: Error: Unsupported inline HTML element: #comment
    at inlineTokenRules.html_inline (/usr/lib/node_modules/md2gslides/lib/extract_slides.js:274:23)
    at processMarkdownToken (/usr/lib/node_modules/md2gslides/lib/extract_slides.js:84:9)
    at inlineTokenRules.inline (/usr/lib/node_modules/md2gslides/lib/extract_slides.js:229:13)
    at processMarkdownToken (/usr/lib/node_modules/md2gslides/lib/extract_slides.js:84:9)
    at processTokens (/usr/lib/node_modules/md2gslides/lib/extract_slides.js:73:9)
    at extractSlides (/usr/lib/node_modules/md2gslides/lib/extract_slides.js:61:5)
    at SlideGenerator.generateFromMarkdown (/usr/lib/node_modules/md2gslides/lib/slide_generator.js:86:27)
    at generateSlides (/usr/lib/node_modules/md2gslides/bin/md2gslides.js:179:27)
    at tryCallOne (/usr/lib/node_modules/md2gslides/node_modules/promise/lib/core.js:37:12)
    at /usr/lib/node_modules/md2gslides/node_modules/promise/lib/core.js:123:15
    at flush (/usr/lib/node_modules/md2gslides/node_modules/asap/raw.js:50:29)
    at process._tickCallback (internal/process/next_tick.js:61:11)
Error: Unsupported inline HTML element: #comment
    at inlineTokenRules.html_inline (/usr/lib/node_modules/md2gslides/lib/extract_slides.js:274:23)
    at processMarkdownToken (/usr/lib/node_modules/md2gslides/lib/extract_slides.js:84:9)
    at inlineTokenRules.inline (/usr/lib/node_modules/md2gslides/lib/extract_slides.js:229:13)
    at processMarkdownToken (/usr/lib/node_modules/md2gslides/lib/extract_slides.js:84:9)
    at processTokens (/usr/lib/node_modules/md2gslides/lib/extract_slides.js:73:9)
    at extractSlides (/usr/lib/node_modules/md2gslides/lib/extract_slides.js:61:5)
    at SlideGenerator.generateFromMarkdown (/usr/lib/node_modules/md2gslides/lib/slide_generator.js:86:27)
    at generateSlides (/usr/lib/node_modules/md2gslides/bin/md2gslides.js:179:27)
    at tryCallOne (/usr/lib/node_modules/md2gslides/node_modules/promise/lib/core.js:37:12)
    at /usr/lib/node_modules/md2gslides/node_modules/promise/lib/core.js:123:15
    at flush (/usr/lib/node_modules/md2gslides/node_modules/asap/raw.js:50:29)
    at process._tickCallback (internal/process/next_tick.js:61:11)
{}
```

Just trying to see everything md2googleslides supports in markdown.

Thanks

**Comment by while1malloc0** [comment]
I had this same issue and it turned out that it was due to a lack of newline between the comment and the `---` that designates the slide break. In general it seems like the markdown lexer is sensitive to newlines being put between a slide break and content that needs to be parsed. Hope this helps.

**Comment by zenmaster24** [comment]
> I had this same issue and it turned out that it was due to a lack of newline between the comment and the `---` that designates the slide break. In general it seems like the markdown lexer is sensitive to newlines being put between a slide break and content that needs to be parsed. Hope this helps.

Cheers while1malloc0 - that was it!
