### ISSUE TITLE
ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by huoenter** [gsuitedevs/md2googleslides#72]
I've been having this error since noon. Tried on different computers.

Unable to generate slides: { Error: ESOCKETTIMEDOUT
    at ClientRequest.<anonymous> (/usr/local/lib/node_modules/md2gslides/node_modules/request/request.js:816:19)
    at Object.onceWrapper (events.js:281:20)
    at ClientRequest.emit (events.js:193:13)
    at TLSSocket.emitRequestTimeout (_http_client.js:669:40)
    at Object.onceWrapper (events.js:281:20)
    at TLSSocket.emit (events.js:193:13)
    at TLSSocket.Socket._onTimeout (net.js:450:8)
    at listOnTimeout (internal/timers.js:535:17)
    at processTimers (internal/timers.js:479:7) code: 'ESOCKETTIMEDOUT', connect: false }

**Comment by jpoehnelt** [comment]
Closing this issue as the repository is archived.
